#!/usr/bin/env kotlinr

/**
 * Generates the Codex agent files from the Claude Code agent files.
 *
 * An agent is written once, as `plugins/<plugin>/agents/<name>.md`. Claude Code discovers that
 * directory on its own. Codex cannot load agents from a plugin at all, so the same agent has to ship
 * a second time as a `.toml` that the `install-codex-agents` skill copies into a Codex agents
 * directory. This script produces that second copy, so the two cannot drift.
 *
 * Do not edit the generated `.toml` files. Edit the `.md` and run this script.
 *
 * The generated files are shipped artifacts: nothing runs this script at install time, so the result
 * must be committed. Run it before releasing whenever an agent changed.
 *
 * Usage:
 *   ./scripts/sync-agents.main.kts
 */

import java.io.File
import kotlin.system.exitProcess

fun fail(message: String): Nothing {
    System.err.println(message)
    exitProcess(1)
}

val repoRoot = generateSequence(File(System.getProperty("user.dir")).absoluteFile) { it.parentFile }
    .firstOrNull { File(it, ".claude-plugin/marketplace.json").isFile }
    ?: fail("not inside the kortex repository")

/** Tools that write. An agent that cannot reach any of them runs read-only under Codex. */
val writingTools = setOf("Write", "Edit", "NotebookEdit", "MultiEdit")

class Agent(val source: File, val name: String, val description: String, val sandbox: String, val body: String)

class SyncPlan(
    val assets: File,
    val rendered: List<Pair<File, String>>,
    val stale: List<File>,
)

/** TOML basic string: the only escapes a one-line description can need. */
fun quote(value: String): String = value
    .replace("\\", "\\\\")
    .replace("\"", "\\\"")
    .replace("\n", "\\n")
    .let { "\"$it\"" }

fun parse(file: File): Agent {
    val text = file.readText()
    val lines = text.lines()
    if (lines.firstOrNull()?.trim() != "---") fail("$file: no YAML frontmatter")
    val end = lines.drop(1).indexOfFirst { it.trim() == "---" }
        .takeIf { it >= 0 }
        ?.plus(1)
        ?: fail("$file: frontmatter is not closed")

    val fields = lines.subList(1, end)
        .filter { it.contains(':') && !it.startsWith(" ") }
        .associate { line ->
            val key = line.substringBefore(':').trim()
            key to line.substringAfter(':').trim()
        }

    val name = fields["name"] ?: fail("$file: frontmatter has no `name`")
    if (name != file.name.removeSuffix(".md")) fail("$file: `name` must match the file name")
    val description = fields["description"] ?: fail("$file: frontmatter has no `description`")
    // A block scalar (`description: |`) would parse as its marker and ship silently as the description.
    if (description.isEmpty() || description in setOf("|", ">", "|-", ">-")) {
        fail("$file: `description` must be a single-line value, not a YAML block scalar")
    }

    // No `tools` means every tool, writing ones included.
    val tools = fields["tools"]?.split(',')?.map { it.trim() }
    val sandbox = when {
        tools == null -> "workspace-write"
        tools.any { it in writingTools } -> "workspace-write"
        else -> "read-only"
    }

    val body = lines.drop(end + 1).joinToString("\n").trim()
    if (body.isEmpty()) fail("$file: body is empty")
    if (body.contains("'''")) fail("$file: body contains ''' and cannot go into a TOML literal string")
    if (body.endsWith("'")) fail("$file: body ends with a quote and cannot close a TOML literal string")

    return Agent(file, name, description, sandbox, body)
}

fun render(agent: Agent, source: String): String = buildString {
    appendLine("# Generated by scripts/sync-agents.main.kts from $source")
    appendLine("# Do not edit. Edit the agent's .md file and re-run the script.")
    appendLine("#")
    appendLine("# Codex identifies the agent by its `name` field, not by the file name.")
    appendLine("# Install with the plugin's `install-codex-agents` skill.")
    appendLine()
    appendLine("name = ${quote(agent.name)}")
    appendLine("description = ${quote(agent.description)}")
    appendLine("sandbox_mode = ${quote(agent.sandbox)}")
    appendLine()
    appendLine("developer_instructions = '''")
    appendLine(agent.body)
    appendLine("'''")
}

val plugins = (File(repoRoot, "plugins").listFiles() ?: emptyArray())
    .filter { File(it, "agents").isDirectory }
    .sortedBy { it.name }

if (plugins.isEmpty()) fail("no plugin ships an agents/ directory")

var written = 0
var removed = 0

// Validate and render the whole tree before touching any generated file. A broken agent in a later
// plugin must not leave earlier plugins half-synced.
val plans = plugins.mapNotNull { plugin ->
    val sources = (File(plugin, "agents").listFiles() ?: emptyArray())
        .filter { it.isFile && it.name.endsWith(".md") }
        .sortedBy { it.name }
    if (sources.isEmpty()) return@mapNotNull null

    val skill = File(plugin, "skills/install-codex-agents")
    if (!skill.isDirectory) {
        fail("${plugin.name} ships agents but has no `skills/install-codex-agents` skill to carry them into Codex")
    }
    val assets = File(skill, "assets")
    if (assets.exists() && !assets.isDirectory) fail("$assets: expected a directory")

    val agents = sources.map(::parse)
    val rendered = agents.map { agent ->
        val target = File(assets, "${agent.name}.toml")
        val content = render(agent, agent.source.relativeTo(repoRoot).path)
        target to content
    }
    val expected = rendered.map { (target, _) -> target.name }.toSet()
    val stale = assets.listFiles().orEmpty()
        .filter { it.name.endsWith(".toml") && it.name !in expected }

    SyncPlan(assets, rendered, stale)
}

for (plan in plans) {
    if (!plan.assets.isDirectory && !plan.assets.mkdirs()) fail("cannot create ${plan.assets}")

    for ((target, content) in plan.rendered) {
        if (target.isFile && target.readText() == content) continue
        target.writeText(content)
        written++
        println("  ${target.relativeTo(repoRoot).path}")
    }

    for (stale in plan.stale) {
        stale.delete()
        removed++
        println("  removed ${stale.relativeTo(repoRoot).path}")
    }
}

println()
println(
    when {
        written == 0 && removed == 0 -> "Already in sync."
        else -> "$written written, $removed removed. Review with `git diff`, then commit."
    }
)
